name: Feature request
description: Suggest a change or addition
labels: [enhancement]
body:
  - type: textarea
    id: need
    attributes:
      label: What are you trying to do?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: What would you like to see?
  - type: textarea
    id: alternatives
    attributes:
      label: What do you do today?
